### PR TITLE
jQuery from site not local for display on page

### PR DESCRIPTION
**Pull request by cha2251**
Pretty sure this should fix the navbar not showing on the page

### CODE REVIEW

**Comment by DavidTheFighter** [comment]
@cha2251 If we're now getting jquery from a CDN now I think it makes sense to delete our local copy. Otherwise I think it should work!

**Review by DavidTheFighter — CHANGES_REQUESTED** [review]
Ahhh that's where this is. Same thing as in the comment in the PR!

**Comment by cha2251** [comment]
Yeah I will, I want to confirm that this fixes it first though

**Review by DavidTheFighter — APPROVED** [review]
Ok!

**Pull request merged**
